# Generated by Django 4.2 on 2024-07-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_guestbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='title',
        ),
    ]
